### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by DWISAx13** [helmisatria/tweet-harvest#2]
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
    at C:\Users\dwiya\AppData\Local\npm-cache\_npx\b456e97c96423ae5\node_modules\tweet-harvest\dist\crawl.js:130:54
    at step (C:\Users\dwiya\AppData\Local\npm-cache\_npx\b456e97c96423ae5\node_modules\tweet-harvest\dist\crawl.js:56:23)
    at Object.next (C:\Users\dwiya\AppData\Local\npm-cache\_npx\b456e97c96423ae5\node_modules\tweet-harvest\dist\crawl.js:37:53)
    at step (C:\Users\dwiya\AppData\Local\npm-cache\_npx\b456e97c96423ae5\node_modules\tweet-harvest\dist\crawl.js:41:139)
    at Object.next (C:\Users\dwiya\AppData\Local\npm-cache\_npx\b456e97c96423ae5\node_modules\tweet-harvest\dist\crawl.js:37:53)
    at fulfilled (C:\Users\dwiya\AppData\Local\npm-cache\_npx\b456e97c96423ae5\node_modules\tweet-harvest\dist\crawl.js:28:58) {
  name: 'TimeoutError'
}

Node.js v18.16.0
```

pas harvest ditengah jalan, berlaku juga ketika manual ` npx tweet-harvest@0.0.29 -s "Prabowo Subianto" -f 01-01-2023 -t 06-05-2023`

**Comment by helmisatria** [comment]
Nice info, per commit ini https://github.com/helmisatria/tweet-harvest/commit/00568aae26c67fcf0369c1cdaca156f19415f485 harusnya udah resolved yaa. Boleh dicoba lagi.

Well tested on my Mac, demo: https://user-images.githubusercontent.com/15356855/236688887-4f3c396b-fbc3-4f8b-9b6c-f5c3c36de81e.mp4

**Comment by DWISAx13** [comment]
error lagi gan

`node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator('div[aria-label="From"]')
============================================================
    at C:\Users\dwiya\AppData\Local\npm-cache\_npx\aa2517cad195aa1e\node_modules\tweet-harvest\dist\crawl.js:365:55
    at step (C:\Users\dwiya\AppData\Local\npm-cache\_npx\aa2517cad195aa1e\node_modules\tweet-harvest\dist\crawl.js:56:23)
    at Object.next (C:\Users\dwiya\AppData\Local\npm-cache\_npx\aa2517cad195aa1e\node_modules\tweet-harvest\dist\crawl.js:37:53)
    at fulfilled (C:\Users\dwiya\AppData\Local\npm-cache\_npx\aa2517cad195aa1e\node_modules\tweet-harvest\dist\crawl.js:28:58) {
  name: 'TimeoutError'
}`

**Comment by DWISAx13** [comment]
error again

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator('div[aria-label="From"]')
============================================================
    at C:\Users\dwiya\AppData\Local\npm-cache\_npx\aa2517cad195aa1e\node_modules\tweet-harvest\dist\crawl.js:365:55
    at step (C:\Users\dwiya\AppData\Local\npm-cache\_npx\aa2517cad195aa1e\node_modules\tweet-harvest\dist\crawl.js:56:23)
    at Object.next (C:\Users\dwiya\AppData\Local\npm-cache\_npx\aa2517cad195aa1e\node_modules\tweet-harvest\dist\crawl.js:37:53)
    at fulfilled (C:\Users\dwiya\AppData\Local\npm-cache\_npx\aa2517cad195aa1e\node_modules\tweet-harvest\dist\crawl.js:28:58) {
  name: 'TimeoutError'
}
```

**Comment by helmisatria** [comment]
@DWISAx13 please make sure you're using the latest version. Try again with this command for example: `npx tweet-harvest@0.0.35 -s "Prabowo Subianto" -f 01-01-2023 -t 06-05-2023 `
