### ISSUE TITLE
input[name="allOfTheseWords"] Not Found

### ISSUE THREAD

**Issue by helmisatria** [helmisatria/tweet-harvest#3]
bang ini pakai yang 0.0.20 sama 0.0.29 terus chromium muncul buka web twitter terus nutup lagi, terus muncul kayak gini

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator('input[name="allOfTheseWords"]')
  locator resolved to <input value="" dir="auto" type="text" autocorrect="on"…/>
attempting click action
  waiting for element to be visible, enabled and stable
============================================================
    at C:\Users\Dibya\AppData\Local\npm-cache\_npx\3c06dd1aee42c42e\node_modules\tweet-harvest\dist\crawl.js:381:47
    at step (C:\Users\Dibya\AppData\Local\npm-cache\_npx\3c06dd1aee42c42e\node_modules\tweet-harvest\dist\crawl.js:56:23)
    at Object.next (C:\Users\Dibya\AppData\Local\npm-cache\_npx\3c06dd1aee42c42e\node_modules\tweet-harvest\dist\crawl.js:37:53)
    at fulfilled (C:\Users\Dibya\AppData\Local\npm-cache\_npx\3c06dd1aee42c42e\node_modules\tweet-harvest\dist\crawl.js:28:58) {
  name: 'TimeoutError'
}

Node.js v18.16.0

**Comment by helmisatria** [comment]
it should be resolved in: by this commit https://github.com/helmisatria/tweet-harvest/commit/13f9d6bebae56bd75823b4d7fe08887f76f089ac
